#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Generate a single-column SA-AT dynamic intensity generalization table."""

from __future__ import annotations

import csv
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Tuple

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from project_paths import ARTIFACTS_ROOT, DOCS_ROOT  # noqa: E402


CONFIG_NAME = "n300_w30_h200_t1500"
METHOD_TAG = "ours"
ARRIVAL_RATES: Tuple[float, ...] = (0.5, 1.0, 2.0, 3.0, 4.0)
EXPECTED_INSTANCES = 50

RESULTS_ROOT = ARTIFACTS_ROOT / "results" / "sa_at_dynamic_intensity"
OUTPUT_DIR = DOCS_ROOT / "tables"
OUTPUT_TEX = OUTPUT_DIR / "sa_at_dynamic_intensity_generalization_generated.tex"
PREVIEW_TEX = OUTPUT_DIR / "sa_at_dynamic_intensity_generalization_preview.tex"
SUMMARY_CSV = OUTPUT_DIR / "sa_at_dynamic_intensity_generalization_summary.csv"


@dataclass(frozen=True)
class MetricSpec:
    key: str
    header: str
    scale: float = 1.0
    decimals: int = 1


METRICS: Tuple[MetricSpec, ...] = (
    MetricSpec("deadline_satisfaction_rate", "DSR (\\%)", 100.0, 1),
    MetricSpec("avg_deadline_violation", "ADV", 1.0, 1),
    MetricSpec("makespan", "Makespan", 1.0, 1),
    MetricSpec("avg_flow_time", "\\makecell{Avg. Flow\\\\Time}", 1.0, 1),
    MetricSpec("total_planning_time", "\\makecell{Planning\\\\Time (s)}", 1.0, 2),
)


def lambda_dir_name(arrival_rate: float) -> str:
    return f"lambda_{arrival_rate:.1f}".replace(".", "p")


def result_path(arrival_rate: float) -> Path:
    return RESULTS_ROOT / lambda_dir_name(arrival_rate) / METHOD_TAG / f"{CONFIG_NAME}_results.json"


def load_rows(arrival_rate: float) -> List[dict]:
    path = result_path(arrival_rate)
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8") as f:
        rows = json.load(f)
    return rows if isinstance(rows, list) else []


def metric_values(rows: List[dict], spec: MetricSpec) -> np.ndarray:
    values = []
    for row in rows:
        if spec.key not in row or not isinstance(row[spec.key], (int, float)):
            continue
        value = float(row[spec.key])
        if (
            spec.key == "avg_deadline_violation"
            and row.get("avg_deadline_violation_scope") != "completed_tasks"
            and isinstance(row.get("deadline_violation_rate"), (int, float))
        ):
            value *= float(row["deadline_violation_rate"])
        values.append(value * spec.scale)
    return np.asarray(values, dtype=float)


def summarize_metric(rows: List[dict], spec: MetricSpec) -> Tuple[float, float, int] | None:
    values = metric_values(rows, spec)
    if values.size == 0:
        return None
    return float(values.mean()), float(values.std(ddof=0)), int(values.size)


def render_summary_cell(summary: Tuple[float, float, int] | None, decimals: int) -> str:
    if summary is None:
        return "--"
    mean, std, _count = summary
    return f"{mean:.{decimals}f}$\\pm${std:.{decimals}f}"


def collect_summary_rows() -> List[dict]:
    summary_rows: List[dict] = []
    for arrival_rate in ARRIVAL_RATES:
        rows = load_rows(arrival_rate)
        source_path = result_path(arrival_rate)
        row = {
            "arrival_rate": arrival_rate,
            "config_name": CONFIG_NAME,
            "method": "BASAR",
            "source_path": str(source_path.relative_to(ROOT)),
            "instances": len(rows),
        }
        for spec in METRICS:
            summary = summarize_metric(rows, spec)
            if summary is None:
                row[f"{spec.key}_mean"] = ""
                row[f"{spec.key}_std"] = ""
                row[f"{spec.key}_count"] = 0
            else:
                mean, std, count = summary
                row[f"{spec.key}_mean"] = mean
                row[f"{spec.key}_std"] = std
                row[f"{spec.key}_count"] = count
        summary_rows.append(row)
    return summary_rows


def render_table() -> str:
    rows_by_rate = {arrival_rate: load_rows(arrival_rate) for arrival_rate in ARRIVAL_RATES}
    if all(len(rows_by_rate[arrival_rate]) == EXPECTED_INSTANCES for arrival_rate in ARRIVAL_RATES):
        instance_phrase = f"over {EXPECTED_INSTANCES} test instances"
    else:
        instance_phrase = "over the evaluated test instances"

    lines = [
        "% Auto-generated by tools/generate_sa_at_dynamic_intensity_table.py",
        "% BASAR-only SA-AT dynamic intensity generalization table.",
        "",
        "\\begin{table}[t]",
        "\\caption{Generalization of BASAR under different dynamic task arrival intensities on SA-AT. "
        "The instance scale is fixed to $A=300$, $S=30$, $I=200$, and $T=1500$; "
        f"only the arrival rate $\\lambda$ is varied. Values are reported as mean$\\pm$standard deviation {instance_phrase}.}}",
        "\\label{tab:sa_at_dynamic_intensity}",
        "\\centering",
        "\\scriptsize",
        "\\setlength{\\tabcolsep}{2.4pt}",
        "\\renewcommand{\\arraystretch}{1.05}",
        "\\resizebox{\\columnwidth}{!}{%",
        "\\begin{tabular}{lccccc}",
        "\\toprule",
        "$\\lambda$ & " + " & ".join(spec.header for spec in METRICS) + " \\\\",
        "\\midrule",
    ]

    for arrival_rate in ARRIVAL_RATES:
        rows = rows_by_rate[arrival_rate]
        cells = [
            render_summary_cell(summarize_metric(rows, spec), spec.decimals)
            for spec in METRICS
        ]
        lines.append(f"{arrival_rate:.1f} & " + " & ".join(cells) + " \\\\")

    lines.extend([
        "\\bottomrule",
        "\\end{tabular}%",
        "}",
        "\\end{table}",
        "",
    ])
    return "\n".join(lines)


def build_preview_document() -> str:
    return "\n".join([
        "\\documentclass[journal]{IEEEtran}",
        "\\usepackage{booktabs}",
        "\\usepackage{makecell}",
        "\\usepackage{graphicx}",
        "\\usepackage[margin=0.7in]{geometry}",
        "\\begin{document}",
        "\\input{sa_at_dynamic_intensity_generalization_generated.tex}",
        "\\end{document}",
        "",
    ])


def write_summary_csv(rows: List[dict]) -> None:
    if not rows:
        return
    fieldnames = list(rows[0].keys())
    with SUMMARY_CSV.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_TEX.write_text(render_table(), encoding="utf-8")
    PREVIEW_TEX.write_text(build_preview_document(), encoding="utf-8")
    summary_rows = collect_summary_rows()
    write_summary_csv(summary_rows)
    print(f"Generated table: {OUTPUT_TEX.relative_to(ROOT)}")
    print(f"Generated preview: {PREVIEW_TEX.relative_to(ROOT)}")
    print(f"Generated summary: {SUMMARY_CSV.relative_to(ROOT)}")
    incomplete = [
        f"lambda={row['arrival_rate']}: n={row['instances']}"
        for row in summary_rows
        if row["instances"] != EXPECTED_INSTANCES
    ]
    if incomplete:
        print("Incomplete result counts: " + ", ".join(incomplete))


if __name__ == "__main__":
    main()
